# Uncomment the next line to define a global platform for your project
platform :ios, ‘9.0’

target 'thRED' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Firebase
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  # Utilities
  pod 'DGActivityIndicatorView'
  pod 'SAMCache'
  pod 'VENTokenField'

  # Messenger
  pod 'JSQMessagesViewController'

  # Pods for thRED

  target 'thREDTests' do
    inherit! :search_paths
    # Pods for testing

    # Firebase
    pod 'Firebase'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'

    # Utilities
    pod 'DGActivityIndicatorView'
    pod 'SAMCache'
    pod 'VENTokenField'
  
    # Messenger
    pod 'JSQMessagesViewController'


  end

  target 'thREDUITests' do
    inherit! :search_paths
    # Pods for testing

    # Firebase
    pod 'Firebase'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'

    # Utilities
    pod 'DGActivityIndicatorView'
    pod 'SAMCache'
    pod 'VENTokenField'

    # Messenger
    pod 'JSQMessagesViewController'
 
 end

end
